config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :index, :show]

  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end

  root to: redirect("/cats")
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :cats
  has_many :cat_rental_requests

  def self.find_by_credentials(user_name, password)
    user = User.find_by(username: user_name)
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:new]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>

<form action="<%=users_url%>" method="post">
  <input type ='hidden' name='authenticity_token' value ="<%=form_authenticity_token%>"/>
  <input type ='text' name ='user[username]' placeholder = "username"/>
  <input type ='password' name ='user[password]' placeholder ="password"/>
  <input type ='submit'/>
</form>

app/views/users/show.html.erb
<header>
  <h1> Hi, <%= @user.username %> </h1>
</header>